name: PartyChat
version: 3.1.1-BETA
main: me.majekdor.partychat.PartyChat
api-version: 1.16
authors: [ Majekdor ]
description: Easily chat among your friends in a party without any commands.
website: https://github.com/Majekdor/PartyChat
commands:
  partychat:
    description: Toggle party chat.
    aliases: [pc]
  party:
    description: Party management commands.
    aliases: [p]
  spy:
    description: Admin spy command.
    aliases: [partyspy]
  pcreload:
    description: Reload the plugin.

permissions:
  partychat.admin:
    description: Allows use of spy and reload command.
    default: op
  partychat.use:
    description: Allows use of PartyChat if use-permissions is enabled in the config.
