name: PartyChat
version: 2.4.0
main: Me.Majekdor.PartyChat.PartyChat
api-version: '1.16'
authors: [Majekdor]
description: 'Plugin that allows players to chat like normal but only among a specific group.'
commands:
  partychat:
    description: Toggle party chat.
    aliases: [pc]
  party:
    description: Party management commands.
    aliases: [p]
  spy:
    description: Admin spy command.
    aliases: [partyspy]
  pcreload:
    description: Reload the plugin.